// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package pea.example.grpc.hello



object HelloProto extends _root_.com.trueaccord.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.com.trueaccord.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_]] = Seq(
    pea.example.grpc.hello.HelloRequest,
    pea.example.grpc.hello.HelloResponse
  )
  private lazy val ProtoBytes: Array[Byte] =
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CgtoZWxsby5wcm90bxIQcGVhLmV4YW1wbGUuZ3JwYyIqCgxIZWxsb1JlcXVlc3QSGgoIZ3JlZXRpbmcYASABKAlSCGdyZWV0a
  W5nIiUKDUhlbGxvUmVzcG9uc2USFAoFcmVwbHkYASABKAlSBXJlcGx5MlsKDEhlbGxvU2VydmljZRJLCghTYXlIZWxsbxIeLnBlY
  S5leGFtcGxlLmdycGMuSGVsbG9SZXF1ZXN0Gh8ucGVhLmV4YW1wbGUuZ3JwYy5IZWxsb1Jlc3BvbnNlYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}